import numpy as np


def apply_rotor_forces(
    model,
    data,
    thrusts
):
    """
    Apply the four rotor thrusts to the MuJoCo drone.

    Each rotor produces a force along the drone's
    local +Z direction.

    The resulting force and torque are calculated
    directly from:

        F_i = [0, 0, T_i]

        tau_i = r_i x F_i
    """

    thrusts = np.asarray(
        thrusts,
        dtype=float
    )

    if thrusts.shape != (4,):
        raise ValueError(
            "Exactly four rotor thrusts are required."
        )


    # ======================================================
    # DRONE BODY
    # ======================================================

    drone_id = model.body(
        "drone"
    ).id


    # ======================================================
    # ROTOR POSITIONS
    # ======================================================
    #
    # These positions come directly from drone_model.xml.
    #
    # Rotor 1: (+0.45,  0.00, 0.05)
    # Rotor 2: (-0.45,  0.00, 0.05)
    # Rotor 3: ( 0.00, +0.45, 0.05)
    # Rotor 4: ( 0.00, -0.45, 0.05)
    #
    # Units: metres.
    #
    # ======================================================

    rotor_positions = np.array(
        [
            [0.45,  0.00, 0.05],
            [-0.45, 0.00, 0.05],
            [0.00,  0.45, 0.05],
            [0.00, -0.45, 0.05]
        ]
    )


    # ======================================================
    # INITIALIZE TOTAL FORCE AND TORQUE
    # ======================================================

    total_force_body = np.zeros(3)

    total_torque_body = np.zeros(3)


    # ======================================================
    # CALCULATE CONTRIBUTION FROM EACH ROTOR
    # ======================================================

    for i in range(4):

        # --------------------------------------------------
        # Rotor thrust force.
        #
        # Positive Z is upward in the drone body frame.
        # --------------------------------------------------

        force_body = np.array(
            [
                0.0,
                0.0,
                thrusts[i]
            ]
        )


        # --------------------------------------------------
        # Position vector from drone center to rotor.
        # --------------------------------------------------

        r = rotor_positions[i]


        # --------------------------------------------------
        # Torque generated by this rotor.
        #
        # tau = r x F
        # --------------------------------------------------

        torque_body = np.cross(
            r,
            force_body
        )


        # --------------------------------------------------
        # Add contribution to total.
        # --------------------------------------------------

        total_force_body += (
            force_body
        )

        total_torque_body += (
            torque_body
        )


    # ======================================================
    # CONVERT BODY-FRAME FORCE/TORQUE TO WORLD FRAME
    # ======================================================

    rotation = data.xmat[
        drone_id
    ].reshape(3, 3)


    total_force_world = (
        rotation
        @ total_force_body
    )


    total_torque_world = (
        rotation
        @ total_torque_body
    )


    # ======================================================
    # APPLY TO MUJOCO
    # ======================================================

    data.xfrc_applied[
        drone_id,
        0:3
    ] = total_force_world


    data.xfrc_applied[
        drone_id,
        3:6
    ] = total_torque_world